/**
 * Funny spinning quotes shown during build/loading operations.
 * Rotated randomly every few seconds while waiting.
 */

const UNIVERSAL_QUOTES = [
  'Pray this works...',
  'You can always just buy a Mac, you know',
  'Project is still WIP, don\'t roast us on Reddit',
  'Hey the guy on Reddit, I\'m trying my best',
  'Docs are still the best way to do this',
  'If it fails, try reading the guides first',
  'Asking Linus Torvalds for permission...',
  'Configuring the flux capacitor...',
  'Downloading more RAM...',
  'Converting your prayers into boot-args...',
  'Negotiating with Apple\'s firmware team...',
  'Teaching your CPU to speak macOS...',
  'Bribing the kernel to cooperate...',
  'Summoning Tim Apple...',
  'This is totally legal, probably',
  'Making Steve Jobs proud... hopefully',
  'One does not simply install macOS',
  'Have you tried turning it off and on again?',
  'This is fine. Everything is fine.',
  'No kexts were harmed in the making of this EFI',
  'Warming up the reality distortion field...',
  'Calculating the meaning of hackintosh...',
  'Polishing the Apple logo on your PC...',
  'Convincing your BIOS this is a real Mac...',
  'Generating config.plist with love and care...',
  'This might take a while. Go grab a coffee.',
  'Or tea. We don\'t judge.',
  'Fun fact: OpenCore has more config options than your BIOS',
  'Remember: patience is a virtue. And a requirement.',
  'If this fails, blame the ACPI tables',
  'Your PC is about to have an identity crisis',
  'Translating PC to Mac... beep boop',
  'Applying digital duct tape...',
  'Compiling hopium...',
  'Loading... unlike your stock macOS installer',
  'Injecting kexts and good vibes...',
  'Making your motherboard believe in itself...',
  'Achievement unlocked: You\'re building a Hackintosh',
  'Hackintosh rule #1: Never update on release day',
  'Hackintosh rule #2: Always have a backup USB',
  'Hackintosh rule #3: Read the Dortania guide. Twice.',
  'SSDT stands for... actually nobody remembers',
  'ACPI: Advanced Configuration and Pray It works',
  'Your GPU is wondering what\'s happening right now',
  'Whispering sweet nothings to the bootloader...',
  'Calibrating ig-platform-id guesswork engine...',
  'Selecting the perfect SMBIOS for your silicon...',
  'Cross-referencing Dortania... again...',
  'Resolving kext dependencies like a puzzle master...',
  'Your ethernet adapter just filed for Mac citizenship',
  'NVMe drive: "Wait, I\'m a Mac drive now?"',
  'USB ports: "There can be only 15!"',
  'Building your EFI is easier than explaining it to friends',
  'Yes, this is an app that makes your PC think it\'s a Mac',
  'No, we can\'t make your webcam work. Sorry.',
  'Thunderbolt hotplug is a myth. Don\'t @ us.',
  'Your fingerprint reader sends its regards... it won\'t work',
  'Almost there... probably... maybe...',
  'This is the fun part. The scary part comes when you boot.',
  'Pro tip: -v boot flag is your best friend',
  'Pro tip: keepsyms=1 debug=0x100 shows panic info',
  'SMBIOS serials: now 100% more random than before',
  'Generating serials that Apple has never seen...',
  'Your AppleID is safe. Probably. We hope.',
  'Fun fact: This app generates better configs than most forums',
  'Remember when hackintoshing meant Clover? Pepperidge Farm remembers.',
  'OpenCore > Clover. Fight me.',
  'Building your digital Frankenstein...',
  'iMessage setup instructions are in the post-install guide. Please.',
  'Did you disable Secure Boot? Please say yes.',
  'Did you disable CSM? PLEASE say yes.',
  'UEFI mode or bust.',
  'Configuring quirks... and there are SO many quirks...',
  'AvoidRuntimeDefrag: true. Always true. Don\'t ask.',
  'SetupVirtualMap: the most confusing boolean in history',
  'ScanPolicy: 0 means "scan everything, I trust nobody"',
  'SecureBootModel: Disabled (for now)',
  'EnableWriteUnprotector vs RebuildAppleMemoryMap: the eternal debate',
  'Quick, look busy — your CPU is watching',
  'Making AppleALC decode your audio codec...',
  'alcid=1? alcid=3? alcid=11? Only one way to find out!',
  'WhateverGreen is doing... whatever green does',
  'Lilu is the backbone of this operation',
  'VirtualSMC: "I am definitely a real Mac SMC"',
  'Your power management profile is being curated...',
  'EC patches: because laptops are special snowflakes',
  'SSDT-PLUG: teaching macOS about your CPU\'s power',
  'agdpmod=pikera: because board IDs are complicated',
  'Checking if your NVMe is one of the naughty ones...',
  'Samsung NVMe: "I promise I\'ll behave this time"',
  'Intel 600p: *nervous laughter*',
  'Optane: "You shall not pass!"',
  'I2C trackpad support: the final boss of laptop hackintoshing',
  'VoodooPS2: making your keyboard feel at home',
  'Building something beautiful from spare parts...',
  'This is the most productive procrastination ever',
  'Your PC is about to live its best life',
  'macOS: because life\'s too short for Windows Update',
  'Think Different (about your hardware)',
  'Designed in California, assembled from your config',
  'One more thing... your EFI is almost ready',
  'The revolution will be kext-loaded',
  'In a world of Windows PCs, be a Hackintosh',
  'Your motherboard manufacturer did NOT sign off on this',
  'ASUS/MSI/Gigabyte support: "We don\'t know her"',
  'Voiding warranties since 2005',
  'This probably violates some EULA somewhere',
  'Compiling boot arguments like a hacker in a movie...',
  'Resolving GitHub API rate limits... please hold',
  'Downloading from acidanthera with gratitude...',
  'Open-source heroes make this possible',
  'Thank you, vit9696, for Lilu and everything else',
  'Inserting witty loading message...',
  'Loading loading messages...',
  'This message will self-destruct in 5... 4...',
  'Are we there yet? Are we there yet?',
  'Patience level: Hackintosh installer',
  'The kext download speed depends on GitHub\'s mood',
  'If GitHub is slow, blame the CDN, not us',
  'Caching your builds so next time is faster...',
  'Your EFI directory structure is being lovingly crafted',
  'OC/Kexts, OC/Drivers, OC/ACPI — a place for everything',
  'config.plist: 1000+ lines of carefully generated XML',
  'Every XML tag placed with surgical precision',
  'BOOTx64.efi: the first thing your PC will see',
  'OpenCore.efi: the brain of the operation',
  'OpenRuntime.efi: the muscle behind the brain',
  'Your PC after this: "I\'m a Mac" / "And I\'m a PC" / "Not anymore"',
  'Plot twist: your Hackintosh will be more stable than a real Mac',
  'Plot twist: it actually works on the first try (rare ending)',
  'Loading... in the style of Apple: slowly but surely',
  'If macOS loads, you earned bragging rights',
  'If macOS doesn\'t load: -v flag, photo of screen, post on Reddit',
  'Remember: every Hackintosh master failed their first build',
  'Thomas Edison failed 1000 times. You only need one good EFI.',
  'The real Hackintosh was the friends we made along the way',
  'Boot from USB → install macOS → never look at Windows again',
  'Configuring audio layout IDs from the ancient scrolls...',
  'Intel Wi-Fi: works with itlwm, not with dreams',
  'Broadcom Wi-Fi: the native path, if you can find the card',
  'Bluetooth: "I work! I work! ...mostly."',
  'HDMI audio: the eternal side quest',
  'DisplayPort: usually just works (famous last words)',
  'Sleep/Wake: the true final boss of hackintoshing',
  'Your CPU fan is nervous about what comes next',
  'Compiling copium for the boot screen...',
  'This took longer to code than you\'d think',
  'We tested this on at least 3 machines. Maybe 4.',
  'Quality assurance: "it works on my machine"',
  'If it panics, try again. Seriously. Sometimes it just works.',
];

const WINDOWS_QUOTES = [
  'Your Windows is Hackintoshing...',
  'Saying bye bye to Windows...',
  'Windows Update can\'t hurt you anymore',
  'No more "Restarting in 15 minutes" pop-ups',
  'BSoD? Never heard of her.',
  'ctrl+alt+del → cmd+opt+esc. Get used to it.',
  'Your C:\\ drive is about to have a sibling',
  'Windows Registry: "I\'ll miss you" / PC: "I won\'t"',
  'Defragmenting your expectations...',
  'Edge: "Hey, try me!" / You: *builds a Hackintosh*',
  'Your Start menu is being replaced by a Dock',
  'Task Manager → Activity Monitor glow-up incoming',
  'PowerShell → Terminal. Same energy, different vibe.',
  'No more Windows Defender false positives',
  'Cortana is being replaced by Siri. Sorry? Not sorry?',
  'Your Windows activation key is crying right now',
];

const LINUX_QUOTES = [
  'Your Linux is Hackintoshing...',
  'Going from "btw I use Arch" to "btw I use macOS"',
  'sudo hackintosh --please-work',
  'apt-get install macos (if only it were that easy)',
  'Your package manager can\'t help you here',
  'From Tux to Apple... it\'s just a different walled garden',
  'Don\'t worry, your Linux partition will still be there',
  'You can still rice macOS. Kind of.',
  'Replacing your tiling WM addiction with Mission Control',
  'systemd → launchd. Same same but different.',
  'The one scenario where Linux users need Windows knowledge',
  '/dev/sda → /dev/disk0. Welcome to Darwin.',
  'chmod +x hackintosh.sh (we wish)',
  'Compiling your macOS kernel... wait no, this isn\'t Gentoo',
  'Your dotfiles are about to get a macOS chapter',
  'iTerm2 is basically Alacritty with extra steps',
];

const MACOS_QUOTES = [
  'Building a Hackintosh... from a Mac. How meta.',
  'Your Mac is helping build another Mac. How generous.',
  'Inception: using macOS to create macOS',
  'Your Mac doesn\'t know you\'re cheating on it',
  'This is like cloning, but for computers',
  'Apple Silicon Mac building an Intel Hackintosh. The irony.',
  'Your real Mac: "Am I a joke to you?"',
  'At least you know the USB installer will work',
  'Privilege: building Hackintosh from native macOS',
  'createinstallmedia? We don\'t need that here.',
  'Your Mac is the best Hackintosh prep machine',
  'Running macOS to escape macOS... wait what?',
];

export type Platform = 'windows' | 'linux' | 'macos' | 'unknown';

export function detectPlatform(): Platform {
  const p = navigator.platform?.toLowerCase() ?? '';
  const ua = navigator.userAgent?.toLowerCase() ?? '';
  if (p.includes('mac') || ua.includes('macintosh')) return 'macos';
  if (p.includes('win') || ua.includes('windows')) return 'windows';
  if (p.includes('linux') || ua.includes('linux')) return 'linux';
  return 'unknown';
}

export function getQuotePool(platform: Platform): string[] {
  const platformQuotes: Record<Platform, string[]> = {
    windows: WINDOWS_QUOTES,
    linux: LINUX_QUOTES,
    macos: MACOS_QUOTES,
    unknown: [],
  };

  return [...UNIVERSAL_QUOTES, ...platformQuotes[platform]];
}

export function getRandomQuote(pool: string[], exclude?: string): string {
  if (pool.length <= 1) return pool[0] ?? '';
  let quote: string;
  do {
    quote = pool[Math.floor(Math.random() * pool.length)];
  } while (quote === exclude && pool.length > 1);
  return quote;
}
