import type { ScanResult } from '../bridge/types';
import { asU64 } from './num';

/**
 * A typical Coffee Lake desktop used by the explicit "demo" mode. The profile
 * goes through the real backend (compatibility, plan, build); only writing a
 * USB drive is disabled while it is active.
 */
export function demoScanResult(): ScanResult {
  return {
    detected: {
      hostOs: 'windows',
      cpu: {
        name: 'Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz',
        vendor: 'GenuineIntel',
        family: 6,
        model: 158,
        stepping: 13,
        cores: 8,
        threads: 8,
        packages: 1,
        baseClockMhz: 3600,
        features: ['sse4_2', 'avx', 'avx2', 'vmx'],
      },
      gpus: [
        {
          name: 'Intel(R) UHD Graphics 630',
          vendorId: '8086',
          deviceId: '3e98',
          subsystemVendorId: '1458',
          subsystemDeviceId: 'd000',
          revision: '02',
          vramMb: null,
          location: { pciPath: 'PciRoot(0x0)/Pci(0x2,0x0)', acpiPath: '\\_SB.PCI0.GFX0' },
        },
        {
          name: 'Radeon RX 580 Series',
          vendorId: '1002',
          deviceId: '67df',
          subsystemVendorId: '1da2',
          subsystemDeviceId: 'e366',
          revision: 'e7',
          vramMb: asU64(8192),
          location: { pciPath: 'PciRoot(0x0)/Pci(0x1,0x0)/Pci(0x0,0x0)', acpiPath: '\\_SB.PCI0.PEG0.PEGP' },
        },
      ],
      audio: [
        {
          name: 'Realtek High Definition Audio',
          codecVendorId: '10ec',
          codecDeviceId: '1220',
          codecSubsystemId: '1458a0c3',
          controllerVendorId: '8086',
          controllerDeviceId: 'a348',
          location: { pciPath: 'PciRoot(0x0)/Pci(0x1f,0x3)', acpiPath: '\\_SB.PCI0.HDAS' },
          isHdmi: false,
          bus: 'hdaudio',
        },
      ],
      network: [
        {
          name: 'Intel(R) Ethernet Connection (7) I219-V',
          kind: 'ethernet',
          bus: 'pci',
          vendorId: '8086',
          deviceId: '15bc',
          subsystemVendorId: '1458',
          subsystemDeviceId: 'e000',
          macAddress: null,
          location: { pciPath: 'PciRoot(0x0)/Pci(0x1f,0x6)', acpiPath: null },
        },
      ],
      input: [
        { name: 'HID Keyboard Device', kind: 'keyboard', bus: 'usb', hardwareId: null, vendor: null },
        { name: 'HID-compliant mouse', kind: 'mouse', bus: 'usb', hardwareId: null, vendor: null },
      ],
      memory: { totalMb: asU64(32768) },
      motherboard: {
        manufacturer: 'Gigabyte Technology Co., Ltd.',
        product: 'Z390 AORUS PRO',
        systemManufacturer: 'Gigabyte Technology Co., Ltd.',
        systemProduct: 'Z390 AORUS PRO',
        lpcVendorId: '8086',
        lpcDeviceId: 'a305',
        chipset: 'Z390',
      },
      storage: [
        {
          name: 'Samsung SSD 970 EVO Plus 1TB',
          kind: 'nvme',
          controllerVendorId: '144d',
          controllerDeviceId: 'a808',
          sizeBytes: asU64(1_000_204_886_016),
        },
      ],
      usbControllers: [],
      chassis: { chassisTypes: [3], manufacturer: 'Gigabyte Technology Co., Ltd.', hasBattery: false, hasLid: false },
      firmware: { uefi: true, secureBoot: false, biosVendor: 'American Megatrends Inc.', biosVersion: 'F12', biosDate: '2021-11-10' },
      acpiTablesDir: null,
      hypervisor: null,
      warnings: [],
    },
    profile: {
      cpu: {
        name: 'Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz',
        vendor: 'intel',
        platform: 'coffee_lake',
        codename: 'Coffee Lake-S',
        family: 6,
        model: 158,
        stepping: 13,
        cores: 8,
        threads: 8,
        isMobile: false,
        hasAvx2: true,
        hasSse42: true,
        isHybrid: false,
      },
      formFactor: 'desktop',
      vm: null,
      gpus: [
        {
          name: 'Intel UHD Graphics 630',
          vendor: 'intel',
          family: 'intel_coffee_lake',
          vendorId: '8086',
          deviceId: '3e98',
          subsystemId: '1458d000',
          isIgpu: true,
          pciPath: 'PciRoot(0x0)/Pci(0x2,0x0)',
          acpiPath: '\\_SB.PCI0.GFX0',
          vramMb: null,
          disabled: false,
        },
        {
          name: 'AMD Radeon RX 580',
          vendor: 'amd',
          family: 'amd_polaris',
          vendorId: '1002',
          deviceId: '67df',
          subsystemId: '1da2e366',
          isIgpu: false,
          pciPath: 'PciRoot(0x0)/Pci(0x1,0x0)/Pci(0x0,0x0)',
          acpiPath: '\\_SB.PCI0.PEG0.PEGP',
          vramMb: asU64(8192),
          disabled: false,
        },
      ],
      audio: {
        codecName: 'Realtek ALC1220',
        codecId: 0x10ec1220,
        controllerVendorId: '8086',
        controllerDeviceId: 'a348',
        controllerPciPath: 'PciRoot(0x0)/Pci(0x1f,0x3)',
        layoutId: null,
      },
      ethernet: [
        {
          name: 'Intel I219-V',
          bus: 'pci',
          vendorId: '8086',
          deviceId: '15bc',
          subsystemId: '1458e000',
          pciPath: 'PciRoot(0x0)/Pci(0x1f,0x6)',
          macAddress: null,
        },
      ],
      wifi: null,
      bluetooth: null,
      input: { keyboardBus: 'usb', touchpadBus: null, touchpadVendor: null, touchpadHid: null, hasTouchscreen: false },
      storage: [
        {
          name: 'Samsung SSD 970 EVO Plus 1TB',
          kind: 'nvme',
          vendorId: '144d',
          deviceId: 'a808',
          sizeBytes: asU64(1_000_204_886_016),
        },
      ],
      motherboardVendor: 'Gigabyte',
      motherboardModel: 'Z390 AORUS PRO',
      chipset: 'Z390',
      ramGb: 32,
      hasBattery: false,
      firmwareUefi: true,
      acpi: null,
      acpiTablesDir: null,
      source: 'demo',
      scanConfidence: 1,
    },
  };
}
