// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AcpiDelete = { comment: string, 
/**
 * 4-char table signature ("SSDT").
 */
tableSignature: string, 
/**
 * 8-char OEM table id ("CpuPm").
 */
oemTableId: string, all: boolean, };
