// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BiosSetting = { name: string, 
/**
 * "enable" | "disable" | a concrete value ("64MB", "UEFI", "AHCI").
 */
value: string, required: boolean, reason: string, locationHint: string | null, };
