// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildPlan } from "./BuildPlan";
import type { KextResult } from "./KextResult";
import type { MacOsVersion } from "./MacOsVersion";
import type { PlatformIdentity } from "./PlatformIdentity";
import type { SsdtResult } from "./SsdtResult";
import type { ValidationResult } from "./ValidationResult";

export type BuildResult = { buildId: string, 
/**
 * Directory that contains the `EFI` folder.
 */
efiPath: string, configPlistPath: string, target: MacOsVersion, opencoreVersion: string, identity: PlatformIdentity, plan: BuildPlan, kexts: Array<KextResult>, ssdts: Array<SsdtResult>, validation: ValidationResult, warnings: Array<string>, };
