// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CpuInfo = { 
/**
 * Brand string ("Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz").
 */
name: string, 
/**
 * "GenuineIntel" | "AuthenticAMD" | "Apple" | other vendor string.
 */
vendor: string, 
/**
 * CPUID display family (base + extended).
 */
family: number | null, 
/**
 * CPUID display model (base + extended << 4).
 */
model: number | null, stepping: number | null, 
/**
 * Physical cores across all packages.
 */
cores: number, threads: number, 
/**
 * Number of CPU packages (sockets).
 */
packages: number, baseClockMhz: number | null, 
/**
 * Lowercase feature flags of interest: "sse4_2", "avx", "avx2", "avx512f", "vmx", "svm".
 */
features: Array<string>, };
