// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlistScalar } from "./PlistScalar";

export type DeviceProperty = { key: string, value: PlistScalar, };
