// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FirmwareCheck } from "./FirmwareCheck";

export type FirmwareReport = { uefiMode: FirmwareCheck, secureBoot: FirmwareCheck, vtX: FirmwareCheck, vtD: FirmwareCheck, above4g: FirmwareCheck, biosVendor: string | null, biosVersion: string | null, confidence: string, };
