// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FirmwareInfo = { uefi: boolean | null, secureBoot: boolean | null, biosVendor: string | null, biosVersion: string | null, biosDate: string | null, };
