// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AcpiFacts } from "./AcpiFacts";
import type { FormFactor } from "./FormFactor";
import type { ProfileAudio } from "./ProfileAudio";
import type { ProfileCpu } from "./ProfileCpu";
import type { ProfileGpu } from "./ProfileGpu";
import type { ProfileInput } from "./ProfileInput";
import type { ProfileNic } from "./ProfileNic";
import type { ProfileStorage } from "./ProfileStorage";
import type { VmKind } from "./VmKind";

/**
 * Canonical, editable description of the target machine. Built by the backend
 * from a scan (or imported / entered manually) and sent back unchanged by the
 * UI for compatibility checks and builds.
 */
export type HardwareProfile = { cpu: ProfileCpu, formFactor: FormFactor, vm: VmKind | null, gpus: Array<ProfileGpu>, audio: ProfileAudio | null, ethernet: Array<ProfileNic>, wifi: ProfileNic | null, bluetooth: ProfileNic | null, input: ProfileInput, storage: Array<ProfileStorage>, motherboardVendor: string, motherboardModel: string, 
/**
 * Chipset / PCH name, e.g. "Z390", "B550", "HM370".
 */
chipset: string | null, ramGb: number, hasBattery: boolean, firmwareUefi: boolean | null, acpi: AcpiFacts | null, 
/**
 * Absolute path of the dumped DSDT.aml (and SSDTs alongside), if available.
 */
acpiTablesDir: string | null, 
/**
 * "scan" | "manual" | "imported" | "demo"
 */
source: string, 
/**
 * 0.0..1.0 — how complete the scan was.
 */
scanConfidence: number, };
