// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginSelection } from "./PluginSelection";

/**
 * One kext bundle (or plugin) to inject.
 */
export type KextSelection = { 
/**
 * Catalog id of the archive that provides this bundle ("VirtualSMC").
 */
catalogId: string, 
/**
 * Top-level bundle inside the archive ("SMCProcessor.kext").
 */
bundle: string, 
/**
 * Plugins inside the bundle to inject, e.g. ("VoodooPS2Keyboard.kext", enabled).
 */
plugins: Array<PluginSelection>, enabled: boolean, minKernel: string | null, maxKernel: string | null, 
/**
 * Build fails if a required kext cannot be fetched.
 */
required: boolean, reason: string, };
