// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Every macOS release an Intel/AMD PC can boot through OpenCore.
 * macOS 26 Tahoe is the final x86 release; macOS 27 is Apple silicon only.
 */
export type MacOsVersion = "10.13" | "10.14" | "10.15" | "11" | "12" | "13" | "14" | "15" | "26";
