// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MotherboardInfo = { 
/**
 * Baseboard manufacturer / product.
 */
manufacturer: string | null, product: string | null, 
/**
 * System (OEM) manufacturer / product name ("Dell Inc." / "XPS 13 9370").
 */
systemManufacturer: string | null, systemProduct: string | null, 
/**
 * LPC/eSPI bridge PCI device id — identifies the PCH ("a305" = Z390).
 */
lpcVendorId: string | null, lpcDeviceId: string | null, 
/**
 * Chipset name if the scanner could resolve it ("Z390").
 */
chipset: string | null, };
