// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NetworkKind } from "./NetworkKind";
import type { PciLocation } from "./PciLocation";

export type NetworkDevice = { name: string, kind: NetworkKind, 
/**
 * "pci" | "usb" | "sdio" | "other"
 */
bus: string, vendorId: string | null, deviceId: string | null, subsystemVendorId: string | null, subsystemDeviceId: string | null, macAddress: string | null, location: PciLocation, };
