// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PciLocation = { 
/**
 * OpenCore device path ("PciRoot(0x0)/Pci(0x1f,0x3)").
 */
pciPath: string | null, 
/**
 * ACPI path ("\\_SB.PCI0.HDAS").
 */
acpiPath: string | null, };
