// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NoteLevel } from "./NoteLevel";

export type PlanNote = { level: NoteLevel, 
/**
 * Component this note is about: "cpu", "gpu", "audio", "wifi", "usb", ...
 */
component: string, title: string, detail: string, };
