// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InputBus } from "./InputBus";
import type { TouchpadVendor } from "./TouchpadVendor";

export type ProfileInput = { keyboardBus: InputBus, touchpadBus: InputBus | null, touchpadVendor: TouchpadVendor | null, 
/**
 * ACPI _HID of the I2C touchpad (e.g. "SYNA2B33", "ELAN0662").
 */
touchpadHid: string | null, hasTouchscreen: boolean, };
