// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MacOsVersion } from "./MacOsVersion";

/**
 * Payload of the `recovery:progress` event.
 */
export type RecoveryProgress = { taskId: string, version: MacOsVersion, 
/**
 * "resolving" | "downloading" | "verifying" | "complete" | "failed"
 */
phase: string, downloaded: bigint, total: bigint | null, 
/**
 * 0.0..1.0 when total is known.
 */
progress: number | null, error: string | null, };
