// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DetectedHardware } from "./DetectedHardware";
import type { HardwareProfile } from "./HardwareProfile";

/**
 * Result of `scan_hardware`: raw facts plus the backend's interpretation.
 */
export type ScanResult = { detected: DetectedHardware, profile: HardwareProfile, };
