// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SmbiosPlan = { model: string, reason: string, 
/**
 * Value for Misc->Security->SecureBootModel ("Disabled", "Default", "j185"...).
 */
secureBootModel: string, 
/**
 * Add the OCLP "Skip Board ID check" booter patches (unsupported model for target).
 */
boardIdSkip: boolean, 
/**
 * Other models that would also work for this machine and target.
 */
alternatives: Array<string>, };
