// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactStatus } from "./ArtifactStatus";

export type SsdtResult = { fileName: string, 
/**
 * "generated" | "oc_sample" | "dortania"
 */
source: string, status: ArtifactStatus, reason: string, };
