// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SsdtSource = { "kind": "generated", aml_hex: string, dsl: string, } | { "kind": "oc_sample", file: string, } | { "kind": "dortania", file: string, };
