// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StorageDevice = { name: string, 
/**
 * "nvme" | "sata" | "raid" | "emmc" | "usb" | "other"
 */
kind: string, controllerVendorId: string | null, controllerDeviceId: string | null, sizeBytes: bigint | null, };
