// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateInfo = { current: string, latest: string | null, updateAvailable: boolean, url: string | null, notes: string | null, };
