// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NoteLevel } from "./NoteLevel";

export type ValidationIssue = { level: NoteLevel, 
/**
 * "ocvalidate" | "layout" | "kext" | "acpi" | "config"
 */
source: string, message: string, path: string | null, };
