// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ValidationIssue } from "./ValidationIssue";

export type ValidationResult = { 
/**
 * True when there is no blocking issue.
 */
valid: boolean, 
/**
 * ocvalidate ran (false when no binary for this host was available).
 */
ocvalidateRan: boolean, ocvalidateOutput: string | null, issues: Array<ValidationIssue>, };
