// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VmKind = "kvm" | "vmware" | "hyper_v" | "virtual_box" | "parallels" | "other";
